### ISSUE TITLE
Embedding on remote site not actually working

### ISSUE THREAD

**Issue by joshreisner** [meeting-guide/react#13]
If you follow the instructions in the README you don't actually get it working. Here is an example:

https://react-demo.meetingguide.org/

Looks like it could be a problem with object merging.

**Comment by mathteacher** [comment]
I don't have any ideas on a solution, but I do have a couple questions to try to better understand the entire situation in general.

1.) https://react.meetingguide.org successfully runs with no significant difference in the code except that the the app.js and style.css are in the root directory themselves instead of coming from another site, so I'm quite confused how the error could even be happening from the exact same code?

2.) Is the https://react.meetingguide.org serving the public folder of the master branch of the react repository? How and when is it updated?

**Comment by joshreisner** [comment]
Haha thanks @mathteacher -- I missed something super-obvious. I was requiring `window.config` to exist but it didn't in the demo. It's fixed now and I added the demo locally so I'll delete the link above. Now it's at https://react.meetingguide.org/demo/

The react.meetingguide.org site is updated automatically when there's a commit on master.
